export const UPDATE_DECK_NAME = 'UPDATE_DECK_NAME';
export const UPDATE_DECK_BG_COLOR = 'UPDATE_DECK_BG_COLOR';

export const CREATE_SLIDE = 'CREATE_SLIDE';
export const REMOVE_SLIDE = 'REMOVE_SLIDE';

export const CREATE_CONTENT = 'CREATE_CONTENT';
export const UPDATE_CONTENT_POSITION = 'UPDATE_CONTENT_POSITION';
export const UPDATE_CONTENT_VALUE = 'UPDATE_CONTENT_VALUE';
